### ISSUE TITLE
Jekyll completely setup but not transferring over now 

### ISSUE THREAD

**Issue by sydneyselch** [sydneyselch/portfolio#2]
I have set up everything correctly with Jekyll (I believe) but it is not connecting my website. At first when I opened up the URL that I copied from the terminal, the website was there and working with the css. Then I began to move things into different folders and now NOTHING is working. I feel like this is something only @thomasjbradley will know how to problem solve! I have attached screenshots of all of my sections.

![screen shot 2015-11-18 at 2 03 58 pm](https://cloud.githubusercontent.com/assets/6373190/11251121/d05a88a2-8dfd-11e5-9576-ec40a4055816.png)
This is what is showing up in the url I can preview it on (Before it showed everything)

![screen shot 2015-11-18 at 2 04 11 pm](https://cloud.githubusercontent.com/assets/6373190/11251118/d058078a-8dfd-11e5-9c51-c27984826511.png)
This is my config doc

![screen shot 2015-11-18 at 2 10 13 pm](https://cloud.githubusercontent.com/assets/6373190/11251183/2550326c-8dfe-11e5-8784-a9c733af83ce.png)
This is my folder setup

![screen shot 2015-11-18 at 2 14 14 pm](https://cloud.githubusercontent.com/assets/6373190/11251304/b0bca1fa-8dfe-11e5-9553-4a9ecf971ec2.png)
This is my index.. Empty aside from the layout

![screen shot 2015-11-18 at 2 04 19 pm](https://cloud.githubusercontent.com/assets/6373190/11251119/d0586360-8dfd-11e5-8582-6ce9d236dba9.png)
This is my _defualt layout file 

![screen shot 2015-11-18 at 2 05 02 pm](https://cloud.githubusercontent.com/assets/6373190/11251120/d058f35c-8dfd-11e5-9045-58c3c8db4d79.png)
this is what it says in the terminal 

![screen shot 2015-11-18 at 2 04 32 pm](https://cloud.githubusercontent.com/assets/6373190/11251117/d05589d8-8dfd-11e5-8305-3511d97bc8a5.png)
This is what an example includes page looks like 

Help please! I'm so close to having it work!

**Comment by thomasjbradley** [comment]
In the index, there's a blank line above the top triple dashes `---` —it can't be there, the dashes must be the very first line.

**Comment by sydneyselch** [comment]
You are a genius. Thank you.
